import os
import re

html_dir = '/home/gntaprdna/Project/signalbot-idx/dashboard/templates'
out_dir = '/home/gntaprdna/Project/orion-alpha-web/src/app'

pages_map = {
    'features.html': 'page.tsx',
    'index_promo.html': 'explore/page.tsx',
    'about.html': 'about/page.tsx',
    'pricing.html': 'pricing/page.tsx',
    'privacy.html': 'privacy/page.tsx',
    'start.html': 'start/page.tsx',
    '404.html': 'not-found.tsx'
}

# Reset globals.css (we will append to it)
# First read the original globals.css without the appended styles
globals_css_path = os.path.join(out_dir, 'globals.css')
if os.path.exists(globals_css_path):
    with open(globals_css_path, 'r') as f:
        original_globals = f.read().split('/* AUTOGENERATED STYLES BELOW */')[0]
else:
    original_globals = ""

with open(globals_css_path, 'w') as f:
    f.write(original_globals + "\n/* AUTOGENERATED STYLES BELOW */\n")

for html_file, tsx_path in pages_map.items():
    full_html = os.path.join(html_dir, html_file)
    if not os.path.exists(full_html):
        continue
        
    with open(full_html, 'r', encoding='utf-8') as f:
        html = f.read()

    # Extract <style>
    style_match = re.search(r'<style[^>]*>(.*?)</style>', html, re.DOTALL | re.IGNORECASE)
    if style_match:
        style_content = style_match.group(1)
        # Convert body class selectors to wrapper class selectors
        style_content = re.sub(r'\bbody\.([a-zA-Z0-9_-]+)', r'.\1', style_content)
        with open(globals_css_path, 'a', encoding='utf-8') as f:
            f.write(f"\n/* Styles from {html_file} */\n{style_content}\n")

    # Extract body attributes and content
    body_match = re.search(r'<body([^>]*)>(.*?)</body>', html, re.DOTALL | re.IGNORECASE)
    if body_match:
        body_attrs = body_match.group(1)
        content = body_match.group(2)
        
        # Get body class
        class_match = re.search(r'class="([^"]+)"', body_attrs)
        wrapper_class = class_match.group(1) if class_match else ""
    else:
        content = html
        wrapper_class = ""

    # Clean content for JSX
    content = re.sub(r'<script\b[^>]*>.*?</script>', '', content, flags=re.DOTALL)
    content = re.sub(r'\bclass=', 'className=', content)
    content = re.sub(r'\bfor=', 'htmlFor=', content)
    content = re.sub(r'stroke-width=', 'strokeWidth=', content)
    content = re.sub(r'stroke-linecap=', 'strokeLinecap=', content)
    content = re.sub(r'stroke-linejoin=', 'strokeLinejoin=', content)
    content = re.sub(r'stroke-dasharray=', 'strokeDasharray=', content)
    content = re.sub(r'preserveAspectRatio=', 'preserveAspectRatio=', content)
    content = re.sub(r'stop-color=', 'stopColor=', content)
    content = re.sub(r'stop-opacity=', 'stopOpacity=', content)

    def style_replacer(match):
        style_str = match.group(1)
        props = []
        for prop in style_str.split(';'):
            if ':' in prop:
                k, v = prop.split(':', 1)
                k = k.strip()
                k = re.sub(r'-([a-z])', lambda m: m.group(1).upper(), k)
                v = v.strip().replace("'", '"')
                props.append(f"{k}: '{v}'")
        return "style={{" + ", ".join(props) + "}}"

    content = re.sub(r'style="([^"]*)"', style_replacer, content)

    # Self-closing tags
    content = re.sub(r'<img([^>]*?)(?<!/)>', r'<img\1 />', content)
    content = re.sub(r'<input([^>]*?)(?<!/)>', r'<input\1 />', content)
    content = re.sub(r'<br([^>]*?)(?<!/)>', r'<br\1 />', content)
    content = re.sub(r'<hr([^>]*?)(?<!/)>', r'<hr\1 />', content)

    # Empty event handlers
    content = re.sub(r'onclick="([^"]*)"', r'onClick={undefined}', content)
    content = re.sub(r'onsubmit="([^"]*)"', r'onSubmit={undefined}', content)
    content = re.sub(r'onchange="([^"]*)"', r'onChange={undefined}', content)
    
    # Remove html comments
    content = re.sub(r'<!--(.*?)-->', r'{/* \1 */}', content, flags=re.DOTALL)
    
    # Check for empty class attributes which break jsx sometimes
    content = re.sub(r'className=""', '', content)

    # Handle wrapper
    if wrapper_class:
        content = f'<div className="{wrapper_class}">\n{content}\n</div>'

    component_name = html_file.split('.')[0].replace('_', ' ').title().replace(' ', '')
    if component_name == '404':
        component_name = 'NotFound'

    jsx = f"""\"\"\"use client\"\"\";

import React, {{ useEffect }} from "react";
import Link from "next/link";

export default function {component_name}Page() {{
  useEffect(() => {{
    const t = localStorage.getItem('orion-theme');
    if (!t) {{
      const defaultTheme = window.matchMedia('(prefers-color-scheme: light)').matches ? 'light' : 'dark';
      document.documentElement.setAttribute('data-theme', defaultTheme);
    }} else {{
      document.documentElement.setAttribute('data-theme', t);
    }}
  }}, []);

  const toggleTheme = () => {{
    const current = document.documentElement.getAttribute('data-theme');
    const next = current === 'dark' ? 'light' : 'dark';
    document.documentElement.setAttribute('data-theme', next);
    localStorage.setItem('orion-theme', next);
  }};

  const toggleMobileMenu = () => {{
    const d = document.getElementById('nav-dropdown');
    const b = document.getElementById('hamburger-btn');
    if (d && b) {{
      const isExpanded = b.getAttribute('aria-expanded') === 'true';
      b.setAttribute('aria-expanded', String(!isExpanded));
      if (isExpanded) {{
        d.classList.remove('is-open');
        setTimeout(() => d.setAttribute('aria-hidden', 'true'), 300);
      }} else {{
        d.setAttribute('aria-hidden', 'false');
        void d.offsetWidth;
        d.classList.add('is-open');
      }}
    }}
  }};

  return (
    <>
      {content}
    </>
  );
}}
"""

    out_file = os.path.join(out_dir, tsx_path)
    os.makedirs(os.path.dirname(out_file), exist_ok=True)
    with open(out_file, 'w', encoding='utf-8') as f:
        f.write(jsx.replace('"""use client"""', '"use client"'))

print("Conversion complete.")
